### ISSUE TITLE
Ops-toolbelt container in terminal pod is not started with privileged security context when specified

### ISSUE THREAD

**Issue by plkokanov** [gardener/dashboard#1050]
**What happened**:
I used the terminal functionality to get a console connection to a cluster's node and I enabled the `privileged` option from the `Terminal Configuration` UI. However, after inspecting the terminal pod I noticed that the ops pod container is not started with a privileged security context.
```
containers:
  - env:
    - name: KUBECONFIG
      value: /mnt/.kube/config
    - name: KUBERNETES_SERVICE_HOST
      value: api.example.com
    image: eu.gcr.io/sap-se-gcr-k8s-public/eu_gcr_io/gardener-project/gardener/ops-toolbelt:0.11.0-mod1
    imagePullPolicy: IfNotPresent
    name: terminal
    resources: {}
    securityContext:
      privileged: false
...
```

**What you expected to happen**:
I expected that the ops-pod container would be started with a privileged security context and to be able to execute commands like listing iptable rules.

**How to reproduce it (as minimally and precisely as possible)**:
Open a terminal, chose cluster as target and from terminal options chose Cluster Terminal Runtime and enable `Privileged`.
Inspect the created pod with kubectl.

**Anything else we need to know**:

**Environment**:
Dashboard version 1.50.2
