### ISSUE TITLE
Show available LB classes in the shoot detail pane for CCloud clusters

### ISSUE THREAD

**Issue by RaphaelVogel** [gardener/dashboard#1057]
Endusers would like to see which LB classes are available, when they create services of type LB.

Domains with more than one subnet will usually have several loadbalancer classes configured in their `cloudprofile` , e.g.
```yaml
  providerConfig:
    constraints:
      floatingPools:
      - name: FloatingIP*
        region: eu-de-2
        loadBalancerClasses:
        - floatingSubnetName: FloatingIP-internet-*
          name: internet
        - floatingSubnetName: FloatingIP-sap-*
          name: sap
          purpose: default
      - name: FloatingIP*
        region: eu-nl-1
        loadBalancerClasses:
        - floatingSubnetName: FloatingIP-internet-*
          name: internet
        - floatingSubnetName: FloatingIP-sap-*
          name: intranet
          purpose: default
```
There can be region specific differences in the LB classes.
Furthermore the user can specify the LB classes to use in the shoot manifest via.
```yaml
spec
  provider:
    type: openstack
    controlPlaneConfig:
        loadBalancerClasses:
        - name: sap
          floatingSubnetName: FloatingIP-sap-*
```
If the user defines the LB classes in the shoot mainfest, they completely replace the ones defined in the
cloudprofile.

After shoot creation the available LB classes should be displayed in the dashboard and read either from the shoot mainfest if configured, or from the cloudprofile.
When reading the Floating Pool and region from the cloudprofile, the best match must be used

In addition there is always one default LB class. This class should be marked in the UI. The following rules apply:
* If only one LB class is defined, it's the default

In case of several LB classes:
If no `purpose: default` is given, we look for a LB class name called `default`.
If this is also not present the first LB class from the list is taken as default
