### ISSUE TITLE
Successful CP migration is shown as operation in progress with reason `Creating resources on new Seed`

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/dashboard#1098]
/kind bug

**What happened**:
Successful CP migration is shown as operation in progress with reason `Creating resources on new Seed`

**What you expected to happen**:
The dashboard to do not show operation in progress after successful CP migration.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Shoot
2. Perform CP migration

3. Make sure that after the CP migration the Shoot status looks like (only relevant fields are shown):

```yaml
status:
  lastOperation:
    lastUpdateTime: '2021-09-14T06:27:05Z'
    progress: 100
    state: Succeeded
    type: Restore
```

4. Make sure that the dashboard still shows progress bar with reason `Creating resources on new Seed`

![Screenshot 2021-09-14 at 9 49 34](https://user-images.githubusercontent.com/9372594/133209468-c38efa12-cb22-41d1-850d-a380f0b93472.png)

**Environment**:
Dashboard version: 1.52.0
