### ISSUE TITLE
`ERR_INFRA_RATE_LIMITS_EXCEEDED` is not properly rendered

### ISSUE THREAD

**Issue by rfranzke** [gardener/dashboard#1101]
**What would you like to be added**:

For a cluster with 

```yaml
lastErrors:
 - codes:
   - ERR_INFRA_RATE_LIMITS_EXCEEDED
```

the error is not properly shown: 
![image](https://user-images.githubusercontent.com/19169361/133992496-9e7a96c1-dfe1-4d42-9fe1-eb5e963d6655.png)

Also, it is not detected as "user issue".
