### ISSUE TITLE
Display failed shoot constraints

### ISSUE THREAD

**Issue by timebertt** [gardener/dashboard#1144]
**What would you like to be added**:

In the shoot status, gardener already publishes the so called "constraints", e.g.
```yaml
status:
  constraints:
    - type: HibernationPossible
      status: 'False'
      lastTransitionTime: '2021-12-08T08:59:44Z'
      lastUpdateTime: '2021-12-08T02:56:17Z'
      reason: ProblematicWebhooks
      message: >-
        ValidatingWebhookConfiguration "opa-validating-webhook" is problematic:
        webhook "validating-webhook.openpolicyagent.org" with failurePolicy
        "Ignore" and 30s timeout might prevent worker nodes from properly
        joining the shoot cluster
    - type: MaintenancePreconditionsSatisfied
      status: 'False'
      lastTransitionTime: '2021-12-08T08:59:44Z'
      lastUpdateTime: '2021-12-08T02:56:17Z'
      reason: ProblematicWebhooks
      message: >-
        ValidatingWebhookConfiguration "opa-validating-webhook" is problematic:
        webhook "validating-webhook.openpolicyagent.org" with failurePolicy
        "Ignore" and 30s timeout might prevent worker nodes from properly
        joining the shoot cluster
```

Also see [documentation](https://github.com/gardener/gardener/blob/master/docs/usage/shoot_status.md#constraints).

It would be good to prominently display failed constraints in the shoot's details page.

**Why is this needed**:

Often times problematic webhook configurations and similar might be the cause for other problems in the cluster (e.g. worker nodes not joining the cluster), that are visible in the dashboard e.g. in the health checks.
- When operators start investigating such issues, it would be helpful to make them aware early on about the failed constraints, because it might speed up the process of investigation.
- When users notice such issues, they might be able to help themselves already by looking at the failed constraint's messages.

/kind enhancement
/area ops-productivity

**Comment by vlerenc** [comment]
Well, the problem is, end users do not do something about these web hooks and so we often end up having manual effort with such clusters (their own web hooks break our operations). So, you are right, I cannot tell you why and it's just an assumption, that how we display that information today is not "triggering them enough" to repair their web hooks.

I cannot tell you from UX perspective, what would work better. Red, explicit text that maintenance will fail, so Tim and I are asking whether you have an idea?

The problem is that forbidding these web hooks (https://github.com/gardener/gardener/issues/3244) isn't trivial either if they and we start fighting/racing (and, it's not possible to have web hook for web hook configurations either). :-(

So, if you have ideas how to make it more prominent (or other ideas) that would be great.

**Comment by grolu** [comment]
Ok, got it. So it is all about making this more prominent.
Just for me to understand this right - The main problem here is that there are clusters where maintenance cannot be triggered due to some webhook configuration. These clusters will not receive updates (and other things that are taken care of during maintenance cannot be performed). Eventually those clusters will break and we have to deal with them, right?

So the solution might be to make the user aware that if he does not take care of this situation the cluster will turn into an error state at some point. Maybe we need a more prominent indicator along with a better explanation.
Please correct me if I'm wrong. Otherwise we will look into this direction.

**Comment by vlerenc** [comment]
> Ok, got it. So it is all about making this more prominent.

@grolu Yes.

> Just for me to understand this right - The main problem here is that there are clusters where maintenance cannot be triggered due to some webhook configuration.

Oh, it's triggered and then it fails. We had a ton of failed clusters now again with the VPN reversal. End user web hooks couldn't be called because VPN was updated and we couldn't update it, because their web hooks blocked our pods in the kube-system namespace. That were many catch22 manual intervention issues of the more ugly kind. But also otherwise, our stuff may not get through and then end users open tickets and we start scratching our heads until we notice their web hooks that break us.

> Eventually those clusters will break and we have to deal with them, right?

Yes.

> So the solution might be to make the user aware that if he does not take care of this situation the cluster will turn into an error state at some point. Maybe we need a more prominent indicator along with a better explanation.
Please correct me if I'm wrong. Otherwise we will look into this direction.

Hmm... interesting idea. Maybe we should indeed mark such clusters as in error and basically say: that's it, you can maintain your clusters now yourselves, but for us it's now hands-off.

WDYT @dguendisch @rfranzke @timebertt ? Instead of a weak condition that everybody ignores or a racing controller "patching" web hooks, how about marking it as failed (we didn't include that as an option in the discussion, did we)? With enough support/explanation in the Dashboard people might then react. Even if they ask questions what this is about, that's much easier and faster to answer than debugging strange "bugs".

**Comment by dguendisch** [comment]
> how about marking it as failed

You mean to have a kind of "fail-fast" and not try to replace components that could fail by faulty webhooks (and then materialize with different other symptoms)?
I like this idea 👍

**Comment by rfranzke** [comment]
What does "marking it as failed" mean technically? 

> and not try to replace components that could fail by faulty webhooks

And what does this mean? Do you want Gardener/GRM to not even try reconciling the system components if such offending webhooks were found?

**Comment by vlerenc** [comment]
> You mean to have a kind of "fail-fast" and not try to replace components that could fail by faulty webhooks (and then materialize with different other symptoms)?

@dguendisch No, I meant (and possibly @grolu as well) to mark the cluster as failed.

@rfranzke This was what I was thinking:

```
status:
  lastOperation:
    description: >-
      You have bad web hooks. Fix them. We won't reconcile your cluster anymore. You are on your own. Enough is enough!
    state: Failed
    type: Reconcile
  lastErrors:
    - description: >-
      You have bad web hooks. Fix them. We won't reconcile your cluster anymore. You are on your own. Enough is enough!
      codes:
        - ERR_BAD_WEB_HOOKS
```

That will make it very clear (different text, but today is April 1st). WDYT?
