### ISSUE TITLE
Adapt to the SecretBinding changes that make the resource provider specific

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/dashboard#1147]
**What would you like to be added**:
Gardener v1.38.0 introduces a new field to the SecretBinding resource - `provider.type`.

```yaml
---
apiVersion: core.gardener.cloud/v1beta1
kind: SecretBinding
metadata:
  name: my-provider-account
  namespace: garden-dev
provider:
  type: <some-provider-name> # {aws,azure,gcp,...}
secretRef:
  name: my-provider-account
```

The field hold information about the cloud provider type. To understand the motivation behind this change, see https://github.com/gardener/gardener/issues/4888.
Gardener v1.38.0 also introduces a new alpha feature gate to the Gardener API Server - `SecretBindingProviderValidation`. For example ,when this feature gate is enabled, the Gardener API Server rejects a CREATE call for a SecretBinding with `provider.type=nil`.

**Tasks:**
- [x] To unblock the enablement and promotion of the `SecretBindingProviderValidation` feature gate, on new SecretBinding creation the dashboard should specify the `provider.type` field -> https://github.com/gardener/dashboard/pull/1154
- [ ] (If applicable) once the `SecretBindingProviderValidation` feature gate is GA (which means that almost all SecretBindings have their `provide.type` field set), the dashboard can make use of the `provider.type` field while showing the cloud provider Secrets in the `Secrets` page.

**Why is this needed**:
To adapt to the changes introduced with gardener/gardener#4888 and to unblock the enablement of the `SecretBindingProviderValidation` feature gate.
