### ISSUE TITLE
Add support for `tokenFile` field and automatic reload for the kubeconfig used in dashboard deployment

### ISSUE THREAD

**Issue by dimityrmirchev** [gardener/dashboard#1157]
**What would you like to be added**:
- Support for `tokenFile` field in the `kubeconfig` that the dashboard deployment is using to connect to the Garden cluster. All other usages of kubeconfigs (where a kubeconfig can be passed from the outside) should not allow the `tokenFile` field.
- Automatic reload of the kubeconfig and the data referenced in it.

Ideally the dashboard should be able to start with a kubeconfig that looks like this:
```yaml
apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: <CA-DATA>
    server: https://server
  name: garden
contexts:
- context:
    cluster: garden
    user: garden
  name: garden
current-context: garden
users:
- name: garden
  user:
    tokenFile: /var/run/secrets/projected/serviceaccount/token
```

A change in the referenced `tokenFile` should also be picked up.

**Why is this needed**:
This is needed in order to take advantage of [service account token volume projection](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#service-account-token-volume-projection). This will eliminate the use of static service account tokens that are never rotated in favor of short-lived tokens which will be renewed and maintained by the `kubelet`.
