### ISSUE TITLE
Cluster cannot be scheduled due to missing service and pod cidr definitions

### ISSUE THREAD

**Issue by kmadac** [gardener/dashboard#1171]
**What happened**: 
When new cluster is created, shoot cluster is not created with scheduler error:

```
{"level":"debug","ts":"2022-03-10T12:14:58.638Z","logger":"events","msg":"Warning","object":{"kind":"Shoot","namespace":"garden-dev","name":"kmdashshoot03","uid":"8550eac8-e516-460b-b8fc-c8bcbf175d3b","apiVersion":"core.gardener.cloud/v1beta1","resourceVersion":"704228"},"reason":"SchedulingFailed","message":"Failed to schedule shoot 'kmdashshoot03': 0/1 seed cluster candidate(s) are eligible for scheduling: {kms02 => invalid networks: [Required value: services is required Required value: pods is required]}"}
```
When I checked the Shoot resource there are missing pod and service cidrs in networking part:

```
    maintenance:
      autoUpdate:
        kubernetesVersion: true
        machineImageVersion: true
      timeWindow:
        begin: 030000+0100
        end: 040000+0100
    networking:
      nodes: 10.250.0.0/16
      type: cilium
    provider:
      controlPlaneConfig:
```

**What you expected to happen**:
I'm able to specify services and pods cidrs, those cidrs will be added to Shoot resource, and cluster will be scheduled.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy gardener and dashboard, create project, secrets and create new cluster.

**Anything else we need to know**:

**Environment**:
Gardener dashboard v1.54.0, k8s v1.23.3, Gardener v1.40.1-dev-d87e49f52facd25715dad2f17bae0b153c78b520-dirty
