### ISSUE TITLE
Random CIDRs when creating AWS shoot with non-default values

### ISSUE THREAD

**Issue by marwinski** [gardener/dashboard#1172]
**What happened**:

I have tried to create an AWS shoot in the Dashboard with non default CIDR ranges. I have set `.spec.provider.infrastructureConfig.networks.vpc.cidr` to `10.180.0.0/16` and `spec.networking.nodes` to `10.180.0.0/16`. When selecting all three zones the following is generated (no matter when CIDRs are specified for the VPC):

```
      networks:
        vpc:
          cidr: 10.180.0.0/16
        zones:
          - name: eu-west-1a
            workers: 10.250.0.0/19
            public: 10.250.32.0/20
            internal: 10.250.48.0/20
          - name: eu-west-1b
            workers: 10.250.64.0/19
            public: 10.250.96.0/20
            internal: 10.250.112.0/20
          - name: eu-west-1c
            workers: 10.250.128.0/19
            public: 10.250.160.0/20
            internal: 10.250.176.0/20
```

**What you expected to happen**:

I expect the following to be generated:
```
      networks:
        vpc:
          cidr: 10.180.0.0/16
        zones:
          - name: eu-west-1a
            workers: 10.180.0.0/19
            public: 10.180.32.0/20
            internal: 10.180.48.0/20
          - name: eu-west-1b
            workers: 10.180.64.0/19
            public: 10.180.96.0/20
            internal: 10.180.112.0/20
          - name: eu-west-1c
            workers: 10.180.128.0/19
            public: 110.180.160.0/20
            internal: 10.180.176.0/20
```

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Anything else we need to know**:

This might be broken for the other cloud providers as well.

**Environment**:

any
