### ISSUE TITLE
Show credential rotation timestamps

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#1204]
**What would you like to be added**:
Gardener puts information about credential rotation timestamps in the shoot status resource:

```yaml
status:
  ...
  credentials:
    rotation:
      certificateAuthorities:
        phase: Prepared
        lastInitiationTime: '2022-05-09T12:01:36Z'
      kubeconfig:
        lastInitiationTime: '2022-05-10T05:47:47Z'
        lastCompletionTime: '2022-05-10T05:51:50Z'
      sshKeypair:
        lastInitiationTime: '2022-05-10T00:18:36Z'
        lastCompletionTime: '2022-05-10T00:24:41Z'
```

**Why is this needed**:
Make this information easier to access and more prominent.
