### ISSUE TITLE
Chart: Increase default memory resource limits and requests

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#1287]
**What would you like to be added**:
Deploying the dashboard in a local kind cluster already shows that it requires more than 300Mi memory

```
kubectl top po -l app=gardener-dashboard --containers
POD                                   NAME                 CPU(cores)   MEMORY(bytes)
gardener-dashboard-5dff7b895b-b4tfz   gardener-dashboard   4m           332Mi
```

I suggest to increase the default requests and limits accordingly and to more sensible values, e.g. to
```yaml
  resources:
    limits:
      cpu: 1.0
      memory: 1G
    requests:
      cpu: 100m
      memory: 350Mi
```

**Why is this needed**:
The default resource limits and requests weren't touched since ~4 years. Meanwhile the dashboard has evolved and we cache several resources (shoots, seeds, cloudprofiles, projects etc). Even on a initially set-up kind cluster ([ref](https://github.com/gardener/gardener/blob/master/docs/development/getting_started_locally.md)) it shows that the dashboard requires more than 300Mi memory.
