### ISSUE TITLE
Tag dashboard image as 'latest'

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#141]
tag dashboard image as latest, so that we can reference it directly [here](https://github.com/gardener/dashboard/blob/master/charts/gardener-dashboard/values.yaml#L8) so that we do not have to update this file after every build
 

> You may now tag images published by our Concourse as 'latest' *in addition* to the effective version by setting the `tag_as_latest` attribute to `true`. Example:

```yaml
...
  traits:
    publish:
      dockerimages:
        some-image-name:
          registry: gcr-readwrite
          image: eu.gcr.io/foo/bar
          dockerfile: Dockerfile
          tag_as_latest: true
...
```
