### ISSUE TITLE
Terminal keeps pending when connecting to node with custom taints

### ISSUE THREAD

**Issue by lizzzcai** [gardener/dashboard#1473]
**What happened**:

Hi colleagues, I have a gpu node which has follow `taint`. When I try to connect to the node via terminal, it shows pending status. When I check  the `term-xxx` pod in my cluster, there are no tolerations added for this taint. I have to manually edit the pod to add it and click the retry in the terminal.

```
  taints:
    - key: nvidia.com/gpu
      value: present
      effect: NoSchedule
```

**What you expected to happen**:

`term-xxx` pod should include tolerations to all taints in the node and terminal connection to the node is successful.

**How to reproduce it (as minimally and precisely as possible)**:

1. create a node with custom taint
2. connect to the node via terminal

**Anything else we need to know**:

existing tolerations in the term-xxx pod:
```
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
```

instead of adding all the taints into tolerations, following toleration can ignore all the taints, just for reference.
```
tolerations:
  - key: "" # An empty key with operator Exists matches all keys, values and effects which means this will tolerate everything.
    operator: Exists
    effect: NoSchedule
```

**Environment**:

* Dashboard1.68.2
