### ISSUE TITLE
Offering Observability (and other) Templated Links/Queries by Use Case

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#1706]
**What would you like to be added**:
@ashwani2k proposed (and showed a text-based interactive prototype) to make it simpler to collect templated links/queries and share them with operators and end users alike. This is especially handy when it comes to Prometheus/Vali(Loki) and the queries. An MCM colleague contributed his personal link/query collection and Ashwani put that into a machine-readable format (see https://gist.github.tools.sap/D043832/325e800e858b6eb4a0b23f21242c0df9, not accessible to everybody, see small excerpt below), e.g.:

```
links:
  title: Observability
  description: "Useful collection of links and queries (with placeholders) for shoot clusters, grouped by categories/use cases, to support Gardener operators in their tasks."
  categories:
  - title: Machines
    description: "Everything around machines, i.e. backing VMs as well as Kubernetes nodes."
    categories:
    - title: Scale Up
      description: "Identify whether scale up was triggered by CA or not."
      queries:
      - title: Check the number of nodes which were scaled up.
        query:
          type: prom
          expression: '"shoot:kube_node_info:count"'
      - title: Check if CA has triggered the scale up.
        query:
          type: vali
          expression: '{container_name="cluster-autoscaler"} |~ "Final scale-up" |~ "shoot--$projectName--$shootName-$worker-pool"'
    - title: Scale Down
      description: "Identify whether scale down was triggered by CA or not."
      queries:
        ...
    - title: Upgrade
      description: Check whether the upgrade is stuck due to any error in MCM or due to PDB violation."
      queries:
      - title: Check for errors for any machine in a worker-pool for a given provider.
        query:
          type: vali
          expression: '{container_name="machine-controller-manager-provider-$provider"} |~ "shoot--$projectName--$shootName-$worker-pool" |~ "machine codes error"'
      - title: Check if drain is stuck due to a PDB violation.
        query:
          type: vali
          expression: '{container_name="machine-controller-manager-provider-$provider"} |~ "could not be evicted from node" |~ "occur due to PDB violation"'
```

It would be great to make those links/queries available in the Gardener Dashboard (maybe also/even https://github.com/gardener/gardenctl-v2, but then more interactive and returning the data into the terminal, e.g. logs to be further processed with grep, sed, awk, etc.) for the benefit of everybody and because the Dashboard is a GUI and Plutono(=Grafana) is one.

**Why is this needed**:
We do not share domain specific knowledge and even if some individuals have personal notes, most often they have them only on one specific subject matter. Newcomers start off with nothing. End users also have nothing and are even further away from our observability stack. All of them would benefit from a curated list of templated links/queries to analyse their issues/understand what puzzles them.
