### ISSUE TITLE
Only offer advertised machine types at cluster creation

### ISSUE THREAD

**Issue by mliepold** [gardener/dashboard#175]
Implement dashboard changes for issue: https://zenhub.mo.sap.corp/app/workspace/o/kubernetes/landscape-setup/issues/76

**Comment by mliepold** [comment]
As discussed with Rafael we will change the flag from ```deprecated```to ```advertised```. See Gardener Issue https://github.com/gardener/gardener/issues/450.
Example:
```
machineTypes:
    - advertised: false 
      name: m4.large
      cpu: "2"
      gpu: "0"
      memory: 8Gi
    - name: m5.large
      cpu: "2"
      gpu: "0"
      memory: 8Gi
```
The default value is true. If the value is false, the machine type won't be offered in the dashboard.
