### ISSUE TITLE
Support multiple session secrets to allow rotation

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#1790]
**What would you like to be added**:
Support for configuring multiple secrets for signing and encrypting user sessions in the Gardener dashboard.

The dashboard backend should accept an array of secrets instead of a single secret. When verifying session cookies, each secret should be tried in order until a valid signature is found. New session cookies should always be signed with the first secret in the list.

Update the dashboard Helm chart and documentation with information on how to configure multiple secrets. 

The secrets should be passed as environment variables to the dashboard deployment. For example:

```yaml
env:
- name: SESSION_SECRET_1
  valueFrom:
    secretKeyRef:
      name: dashboard-session-secret-1
      key: keyValue
- name: SESSION_SECRET_2  
  valueFrom:
    secretKeyRef:
      name: dashboard-session-secret-2
      key: keyValue
```

**Why is this needed**:
Currently, the Gardener dashboard only supports a single secret (passed via the `SESSION_SECRET` environment variable) for signing and encrypting user sessions. This makes it difficult to rotate secrets without invalidating all active user sessions.

Supporting multiple secrets would allow for graceful secret rotation by:
1. Adding a new secret to the beginning of the list (e.g. `SESSION_SECRET_1`)
2. Waiting for old sessions using the previous secret to expire
3. Removing the old secret (e.g. `SESSION_SECRET_2`) from the end of the list

This improves security by enabling regular session secret rotation without disrupting active sessions. It aligns the dashboard session management with best practices.

By enhancing the dashboard to support this functionality, we can provide Gardener operators with a more robust and secure user session implementation that allows secrets to be cycled gracefully without impacting the user experience.
