### ISSUE TITLE
Handle CRDsWithProblematicConversionWebhooks constraint

### ISSUE THREAD

**Issue by lotharbach** [gardener/dashboard#1878]
**What would you like to be added**:
A `Shoot` that has the `CRDsWithProblematicConversionWebhooks` constraint is not correctly displayed. There is no "Error Bubble" but it has an "Issue Since" column.

<img width="1362" alt="Screenshot 2024-05-23 at 14 26 50" src="https://github.com/gardener/dashboard/assets/1708962/90173650-e27c-41ca-96a1-891cba67341b">

**Why is this needed**:
The goal of having those constrains is to inform the user of a misconfiguration/error of his own responsibility inside the Shoot, that could become problematic in the future/under certain circumstances. I wasn't aware of this particular pitfall either and only became aware because of the "Issue Since" not matching the "All Green Bubbles" and I don't think the average user would understand the yaml output and what constraints even are to identify this problem. This error condition could be made more visible and findable in the project list and this information could be shown in the Shoot details page as well.

This is the full constraints list of this Shoot:

```
  constraints:
    - type: HibernationPossible
      status: 'True'
      lastTransitionTime: '2024-05-23T12:07:52Z'
      lastUpdateTime: '2024-05-21T14:59:23Z'
      reason: NoProblematicWebhooks
      message: All webhooks are properly configured.
    - type: MaintenancePreconditionsSatisfied
      status: 'True'
      lastTransitionTime: '2024-05-23T12:07:52Z'
      lastUpdateTime: '2024-05-21T14:59:23Z'
      reason: NoProblematicWebhooks
      message: All webhooks are properly configured.
    - type: CRDsWithProblematicConversionWebhooks
      status: 'False'
      lastTransitionTime: '2024-05-23T12:07:53Z'
      lastUpdateTime: '2024-05-22T15:26:12Z'
      reason: CRDsWithProblematicConversionWebhooks
      message: >-
        Some CRDs in your cluster have multiple stored versions present and have
        a conversion webhook configured: objects.kubernetes.crossplane.io.
        Please see
        https://github.com/gardener/gardener/blob/master/docs/usage/shoot_status.md#constraints
        for more details.
```
