### ISSUE TITLE
`Configure Workers` panel wrongly tries to delete a zone from the infrastructureConfig of an aws Shoot

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/dashboard#2045]
**What happened**:
`Configure Workers` panel wrongly tries to delete a zone from the infrastructureConfig of an aws Shoot

**What you expected to happen**:
`Configure Workers` to do not try to delete a zone from the infrastructureConfig of an aws Shoot

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an AWS with 3 zones in `.spec.provider.infrastructureConfig`
```yaml
    infrastructureConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vpc:
          cidr: 10.180.0.0/16
        zones:
          - name: eu-west-1b
            workers: 10.180.0.0/19
            public: 10.180.32.0/20
            internal: 10.180.48.0/20
          - name: eu-west-1c
            workers: 10.180.64.0/19
            public: 10.180.96.0/20
            internal: 10.180.112.0/20
          - name: eu-west-1a
            workers: 10.180.128.0/19
            public: 10.180.160.0/20
            internal: 10.180.176.0/20
```

and with a worker pool with 2 zones in `.spec.provider.workers`:
```yaml
    workers:
      - cri:
          name: containerd
        name: worker-d9upk
        machine:
          type: m5.large
          image:
            name: gardenlinux
            version: 1443.9.0
          architecture: amd64
        maximum: 3
        minimum: 1
        maxSurge: 1
        maxUnavailable: 0
        volume:
          type: gp3
          size: 50Gi
        zones:
          - eu-west-1b
          - eu-west-1c
        systemComponents:
          allow: true
```

2. From the dashboard, try to update the gardenlinux version of the worker pool using the `Configure Workers` panel.

3. Make sure it fails with:
```
Could not save worker configuration 
admission webhook "validator.admission-aws.extensions.gardener.cloud" denied the request: networks.zones: Forbidden: removing zones is not allowed
```

![Screenshot 2024-08-20 at 10 31 20](https://github.com/user-attachments/assets/305f9e3e-8b78-4b6e-a65c-17ffef458c12)

admission-aws does not allow removal of zone from `.spec.provider.infrastructureConfig.networks.zones`:
https://github.com/gardener/gardener-extension-provider-aws/blob/aeeac045df4e947a199b3e0a0d43efb6a6acc65d/pkg/apis/aws/validation/infrastructure.go#L187-L190

Why the dashboard tries to remove a zone from  `.spec.provider.infrastructureConfig.networks.zones` when it is updating the workers spec?

**Anything else we need to know**:

**Environment**:
Version: 1.76.1
