### ISSUE TITLE
Sort Cloud Profiles

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#207]
The Garden Administrator needs an option to sort cloud profiles. This could be achieved by adding an annotation to all cloud profiles with an integer value. The annotation should be part of the landscape setup. This value could be used by the Gardener Dashboard (and other Tools / UIs) to sort infrastructures, as well as multiple Cloud Profiles within an infrastructure.

Imagine the following Cloud Profiles:

```
apiVersion: garden.sapcloud.io/v1beta1
kind: CloudProfile
metadata:
  name: aws
  annotations:
    garden.sapcloud.io/priority: 200
spec:
  aws:
...
```

```
apiVersion: garden.sapcloud.io/v1beta1
kind: CloudProfile
metadata:
  name: openstack-1
  annotations:
    garden.sapcloud.io/priority: 102
spec:
  openstack:
...
```

```
apiVersion: garden.sapcloud.io/v1beta1
kind: CloudProfile
metadata:
  name: openstack-2
  annotations:
    garden.sapcloud.io/priority: 101
spec:
  openstack:
...
```

Currently they would be ranked like this:

Infrastructures:
- aws
- openstack:
  - openstack-1
  - openstack-2

With the annotation, the dashboard would order the Cloud Profiles like this:

Infrastructures:
- openstack:
  - openstack-2
  - openstack-1
- aws

This feature helps to highlight / promote specific infrastructures or cloud profiles. It could also help reducing costs by ranking cheaper options first.
