### ISSUE TITLE
No operator action required for `CRDsWithProblematicConversionWebhooks`

### ISSUE THREAD

**Issue by acumino** [gardener/dashboard#2108]
**What would you like to be added**:
Currently, clusters with `CRDsWithProblematicConversionWebhooks` condition true are not marked for no operator action required. If this condition is present on the cluster it should be marked for no operator action required.

**Why is this needed**:
This issue occurs when a user has CRDs which doesn't follow best practices, operator can't do anything to fix it. To keep dashboard clean we should mark `CRDsWithProblematicConversionWebhooks` condition true as no operator action required.

**Comment by petersutter** [comment]
Currently, the dashboard checks the error codes under `status.lastErrors`, where there is also `ERR_PROBLEMATIC_WEBHOOK`, which we flag as a user error. What `lastError` is present when the `CRDsWithProblematicConversionWebhooks` condition is true?

**Comment by petersutter** [comment]
ping @acumino

**Comment by acumino** [comment]
`CRDsWithProblematicConversionWebhooks` is just a constraint in shoot status and not an error. It should not be considered for no operator action required since it can lead to other errors being ignored.

```
  constraints:
    - type: CRDsWithProblematicConversionWebhooks
      status: 'False'
      lastTransitionTime: ''
      lastUpdateTime: ''
      reason: CRDsWithProblematicConversionWebhooks
      message: >-
        Some CRDs in your cluster have multiple stored versions present and have
        a conversion webhook configured: <webhook-name>. Please see
        https://github.com/gardener/gardener/blob/master/docs/usage/shoot/shoot_status.md#constraints
        for more details.
```
