### ISSUE TITLE
Dashboard overwrites custom changes to `.spec.infrastructureConfig.zones` when switching between `Overview` and `YAML` pages.

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/dashboard#2188]
**What happened**:
We found that when setting a custom `.spec.networking.nodes`, then setting custom `.spec.infrastructureConfig.zones`, then  switching between `Overview` and `YAML` pages overwrites the changes to the `.spec.infrastructureConfig.zones` field.

This was quite confusing for the end user. There was the impression that this change is done on server side.

**What you expected to happen**:
Custom changes to `.spec.infrastructureConfig.zones` not to be overwritten.

**How to reproduce it (as minimally and precisely as possible)**:
The working part:
1. Click on the new cluster button.
2. Switch to the YAML editor
3. Change `.spec.networking.nodes` from `10.180.0.0/16` to `10.181.0.0/16`. 
4. Switch to the Overview page, then back to the `YAML`. Observe that the `.spec.infrastructureConfig.zones` are adjusted automatically:
```yaml
        zones:
          - name: ap-southeast-1a
            workers: 10.181.0.0/19
            public: 10.181.32.0/20
            internal: 10.181.48.0/20
```

The part that does NOT work as expected:
1. Click on the new cluster button.
2. Switch to the YAML editor
3. Change `.spec.networking.nodes` from `10.180.0.0/16` to `10.181.0.0/24`. Change also `.spec.infrastructureConfig.zones` as follows:
```yaml
        zones:
          - name: ap-southeast-1c
            workers: 10.181.0.0/28
            public: 10.181.32.0/29
            internal: 10.181.48.0/29
```
4. Switch to the Overview page, then back to the `YAML`. Observe that the `.spec.infrastructureConfig.zones` are adjusted silently in unexpected manner to:
```yaml
          - name: ap-southeast-1c
            workers: 10.181.0.0/27
            public: 10.181.0.32/28
            internal: 10.181.0.48/28
```

**Anything else we need to know**:
N/A

**Environment**:
Version: 1.78.0
