### ISSUE TITLE
Show Cluster Metrics on Details Page

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#228]
Discuss if we want to show cluster metrics on the details page of a shoot. We need to clarify for which scenario this is useful (for more detailed metrics, the cluster needs to access Grafana or similar tools anyway).
If we agree to show some (basic) metrics, we need to agree on how to visualize this in an appealing way

**Comment by grolu** [comment]
Maybe also part of #26. Let's see how far we get by leveraging the terminal feature

**Comment by petersutter** [comment]
Using the terminal shortcuts feature you can achieve something like that by configuring a shortcut to have a cluster overview of the deployments, pods, cpu, memory etc. Below is an example using k9s.
```yaml
shortcuts:
- title: Cluster Overview
  description: This gives a quick overview about the status of your cluster
  target: shoot
  container:
    image: quay.io/derailed/k9s:latest
    args:
    - --headless
    - --command=pulses
```
<img width="1870" alt="Screenshot 2020-09-07 at 14 15 13" src="https://user-images.githubusercontent.com/5526658/92387021-23799800-f115-11ea-80a0-baa5a1ea38b3.png">
