### ISSUE TITLE
[Proposal] Hint if Auto-Scaling is Switched Off

### ISSUE THREAD

**Issue by vlerenc** [gardener/dashboard#2289]
**What would you like to be added**:
Some stakeholders would like to statically control the requests of control plane components and node daemon sets. We agreed [here](https://github.com/gardener/gardener/issues/10248#issuecomment-2545907477) that we rather only offer the configuration of VPA `minAllowed` for control plane components (or else it is difficult to provide control planes as a service reliably) and only allow the static configuration of node daemon sets (e.g. https://github.com/gardener/gardener-extension-networking-calico/pull/464, default is VPA) or switching off VPA altogether (https://github.com/gardener/gardener/blob/c59ebdf2c4bb3e2e21af9d15c06fb8c26ad95497/example/90-shoot.yaml#L310, default is `true`).

If that's being used however (auto-scaling is effectively switched off), landscape operators should know about it to not chase a problem that auto-scaling would have prevented. Hence, a disclaimer/warning would be nice to see (maybe similar to `EU Access`?).

**Why is this needed**:
To avoid operators wasting their time on problems that auto-scaling would have prevented.

**Comment by petersutter** [comment]
> If that's being used however (auto-scaling is effectively switched off), landscape operators should know about it to not chase a problem that auto-scaling would have prevented. Hence, a disclaimer/warning would be nice to see

@vlerenc I'm unsure why the `minAllowed` configuration is mentioned. Is it just an example of another autoscaling-related setting, or would it actually help operators to know if it’s set?

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
spec:
  kubernetes:
    etcd:
      main:
        autoscaling:
          minAllowed: # potential hint when set 
            cpu: "2"
            memory: 6Gi
      events:
        autoscaling:
          minAllowed: # potential hint when set 
            cpu: "1"
            memory: 3Gi
    kubeAPIServer:
      autoScaling:
        minAllowed: # potential hint when set 
          cpu: "1"
          memory: 3Gi
```

Otherwise, these are the configurations that we should look out for in order to display a hint (please correct me if I've missed anything):
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
spec:
  networking:
    type: calico
    providerConfig:
      apiVersion: calico.networking.extensions.gardener.cloud/v1alpha1
      kind: NetworkConfig
      autoScaling:
        mode: "static" # hint when set to static
        resources:
          node:
            cpu: 100m
            memory: 100Mi
          typha:
            cpu: 100m
            memory: 100Mi
```

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
spec:
  kubernetes:
    verticalPodAutoscaler:
      enabled: false # hint when disabled
```
