### ISSUE TITLE
Show Control Plane Pods

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#259]
An Operator with access to the Control Plane on the Seed Cluster wants to see the Pods of the Control Plane on the Cluster Details Page. These Pods can be used as entry points for further actions, like opening a terminal directly into the Pod, show logs or events related to a Pod etc.

Exposing logs and events are not part of this issue, but this is kind of a prerequisite to offer them.

**Comment by grolu** [comment]
Part of #139

**Comment by grolu** [comment]
Related to #26

**Comment by petersutter** [comment]
Using the terminal shortcuts feature you can achieve the same by configuring a shortcut to list all nodes. Below is an example using k9s.
```yaml
shortcuts:
- title: Control Plane Pods
  description: View the pods of the control plane for this cluster
  target: cp
  container:
    image: quay.io/derailed/k9s:latest
    - --headless
    - --command=pods
```
<img width="1868" alt="Screenshot 2020-09-07 at 14 54 50" src="https://user-images.githubusercontent.com/5526658/92389843-1d39ea80-f11a-11ea-8e50-d4d2e02fa776.png">
