### ISSUE TITLE
Use ServiceAccount resource for the technical users, instead of User

### ISSUE THREAD

**Issue by vpnachev** [gardener/dashboard#384]
At the moment the technical users created via the dashboard are some kind of a mix between `Users` and `ServiceAccounts`.

The gardener `Project` [resource](https://github.com/gardener/gardener/blob/1f0982a94faa80d1f7c808386d41b8815c3151ff/pkg/apis/garden/v1beta1/types.go#L483) is using the [Subject](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#subject-v1beta1-rbac-authorization-k8s-io) resource to describe the members of a project, which means that a member could be of kind `User`, `Group` or `ServiceAccount`.

The issue is that the dashboard is using subject of kind `User` for service accounts instead of `ServiceAccount`. 

Also, there should be a migration for the current technical users from
```yaml
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: system:serviceaccount:garden-dev:robot
```
to
```yaml
  - apiGroup: ""
    kind: ServiceAccount
    name: robot
    namespace: garden-dev
```
