### ISSUE TITLE
Kubeconfig generation for user garden cluster access

### ISSUE THREAD

**Issue by mvladev** [gardener/dashboard#417]
Today, end-users can get their JWT IDToken in the Account page.
This is a hard process for several reasons 

- they have copy + paste that token in their `kubeconfig` with correct API server address, `ca-cert` and more.
- it's impossible to refresh it (no refresh token is provided).
- end-users have to login via the dashboard (which might not be okay for console users).

Ideally end-users can get a personalized `kubeconfig` when accessing the `Account` page:

```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://MY-GARDEN-CLUSTER
  name: garden-oidc
contexts:
- context:
    cluster: garden-oidc
    user: garden-oidc
  name: garden-oidc
current-context: garden-oidc
kind: Config
preferences: {}
users:
- name: garden-oidc
  user:
    auth-provider:
      config:
        client-id: Test1234
        client-secret: Test1234
        id-token: SOME-ID-TOKEN
        idp-issuer-url: https://my-dex.foo.bar
        refresh-token: MY-REFRESH-TOKEN (applicable in some cases)
        extra-scopes: openid,email,profile,groups # coma separated scopes
      name: oidc
```

With this, end-users can access the garden cluster via `kubectl` and it'll automatically refresh the `id-token` when it expires.

This would also enable uses to use a [odic-login](https://github.com/int128/kubelogin) plugin for their `kubeconfig` in case their `refresh-token` is revoked.

The same approach can also be applied for Shoot clusters with `oidc` configured.
