### ISSUE TITLE
Define FIP subnet pool in shoot creation dialog

### ISSUE THREAD

**Issue by kayrus** [gardener/dashboard#446]
OpenStack cloud profile can contain the following loadbalancer classes:

```yaml
      floatingPools:                                                                                                                                                                                                                               
      - loadBalancerClasses:                                                                                                                                                                                                                       
        - floatingSubnetID: cc4cf15d-dcd3-43bb-bc31-bfd4b9d6996d                                                                                                                                                                                   
          name: internal
        - floatingSubnetID: 1bef59b2-74a5-4f94-aad6-83a59abe2aa0
          name: internet
        name: FloatingIP-external-cp
      - loadBalancerClasses:
        - floatingSubnetID: 42f12acd-244d-486e-8bbf-c58b0cb44619
          name: default
        name: FloatingIP-external-cp-gardener
```

Shoot spec must allow to define the desired subnets, e.g.:

```yaml
spec:
  addons:
    kubernetes-dashboard:
      authenticationMode: basic
      enabled: true
    nginx-ingress:
      enabled: true
  cloud:
    openstack:
      floatingPoolName: FloatingIP-external-cp-gardener
      loadBalancerClasses:
      - floatingSubnetID: d2eda633-e930-464e-b285-ecb826e02861
        name: default
      loadBalancerProvider: f5networks
```
