### ISSUE TITLE
Customize Dashboard personas and permissions

### ISSUE THREAD

**Issue by mvladev** [gardener/dashboard#476]
# Customize Dashboard personas and permissions

The Dashboard has a notion for two set of users:

- Administrators
- Users

## Administrator

The Administrator persona is [determined](https://github.com/gardener/dashboard/blob/03059189bad3422e024f6282ebb7acd08ad16a89/backend/lib/services/authorization.js#L44-L51) if the subject can delete `Shoots` in all namespaces.

In the UI those personas are allowed to view the Operator Grafana and Prometheus and get information about the `Shoot`

## User

The User persona is [determined](https://github.com/gardener/dashboard/blob/03059189bad3422e024f6282ebb7acd08ad16a89/backend/lib/services/authorization.js#L53-L59) if the subject can create `Project`.

In the UI those those personas are allowed to do modifications to the `Shoots` and `Projects` resources and view the user Grafana and Prometheus.

## Problems

- Gardener creates different ClusterRole(Bindings) for completely separate persons - Project Owner and Project Members. This distinction is not addressed in the Dashboard.
- Even if user is allowed to view `Shoots` cluster-wide, the dashboard doesn't display any information.
- For having only [one IDP prosal](https://github.com/gardener/gardener/issues/999), a `SubjectAccessReview` must be send to the Gardener cluster - using a verb such as `get`, `update`, `patch` or `delete` or any other pseudo-verb such as `debug`.

## Proposed solution

A more appropriate solution would be to define an abstract Personas in the RBAC API and display different parts of the UI based on those permissions (which can be made fully customizable).

For example for the abstract Persona `Support` which is allowed only to view `Shoot` clusters the following `ClusterRole` could be defined:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener:support
rules:
- apiGroups:
  - core.gardener.cloud
  - garden.sapcloud.io
  resources:
  - shoots
  verbs:
  - get
  - watch
  - list
  - support
```

here, a new pseudo verb `support` is added to this role which doesn't affect the standard API operations.

A good idea would be to add customization for such personas in the configuration of the dashboard (pseudo code) and showing different parts of the UI if this check is successful or not:

```yaml
personas:
- name: Support
  description: This user is allowed to provide basic support for Shoot clusters
  subjectAccessReview:
    verb: support
    group: garden.sapcloud.io
    resource: shoots
    namespaced: false # do a cluster-wide check or for a the current namespace
```
