### ISSUE TITLE
Show Cluster Nodes

### ISSUE THREAD

**Issue by grolu** [gardener/dashboard#530]
Show actual Nodes per worker group (not only min / max values).
#223 is a prerequisite - we need to watch all resources, also on the shoot apiserver, to be able to display this kind of information

**Comment by petersutter** [comment]
Using the terminal shortcuts feature you can achieve the same by configuring a shortcut to list all nodes. Below is an example using k9s.
```yaml
shortcuts:
- title: "Nodes"
  description: View the nodes for this cluster
  target: shoot
  container:
    image: quay.io/derailed/k9s:latest
    args:
    - --headless
    - --command=nodes
```
<img width="1871" alt="Screenshot 2020-09-07 at 14 04 14" src="https://user-images.githubusercontent.com/5526658/92386228-aa2d7580-f113-11ea-988b-6b4b0a3c9c05.png">
