### ISSUE TITLE
Restrict permissions of dashboard's service user to garden cluster

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#545]
Currently, the dashboard has [cluster-admin](https://github.com/gardener/dashboard/blob/b1c1afd5ca6d3486d78e315eaa664235f4b73c30/charts/gardener-dashboard/templates/rbac.yaml#L11-L14) privileges which is not necessary. 

We should create a new dashboard role that only contains the necessary privileges.

**Comment by petersutter** [comment]
These should be the required privileges for the dashboard. We probably have to split the dashboard chart into application and runtime chart, similar like with the gardener charts

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener-dashboard-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - core.gardener.cloud
  resources:
  - quotas
  verbs:
  - list
  - watch
- apiGroups:
  - core.gardener.cloud
  resources:
  - projects
  verbs:
  - list
  - watch
- apiGroups:
  - core.gardener.cloud
  resources:
  - shoots
  verbs:
  - watch
- apiGroups:
  - apiregistration.k8s.io
  resources:
  - apiservices
  verbs:
  - get
# terminal bootstrapping
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - core.gardener.cloud
  resources:
  - shoots
  verbs:
  - get
```
