### ISSUE TITLE
Dashboard doesn't consider resource quota defined for a Project/Secret.

### ISSUE THREAD

**Issue by swilen-iwanow** [gardener/dashboard#593]
How to reproduce it (as minimally and precisely as possible):

1. Create Quota
 ```
apiVersion: core.gardener.cloud/v1beta1
kind: Quota
metadata:
  name: my-quota
  namespace: garden-dev
spec:
  clusterLifetimeDays: 7
  metrics:
    cpu: "10"
    gpu: "20"
    loadbalancer: "10"
    memory: 40Gi
    storage.premium: 20Gi
    storage.standard: 80Gi
  scope:
    apiVersion: core.gardener.cloud/v1beta1
    kind: Project
```
2. Create SecretBinding
```
apiVersion: core.gardener.cloud/v1beta1
kind: SecretBinding
metadata:
  labels:
    cloudprofile.garden.sapcloud.io/name: gcp
  name: my-secretbinding
  namespace: garden-dev
quotas:
- name: my-quota
  namespace: garden-dev
secretRef:
  name: my-secret
  namespace: garden-dev
```
3. Go to shoot creation in the project
4. Try to use an instance with configurations higher than the quota limits

What happened: 
Creation failed for example: 
- shoots.core.gardener.cloud "vbzow4zil2" is forbidden: Quota limits exceeded. Unable to allocate further gpu memory 

What was expected:
- not be able to use configuration settings that exceed the quota limits.
