### ISSUE TITLE
Should nginxIngress addon needs to be disabled by default?

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/dashboard#596]
Currently if you do not specify the `nginxIngress` addon in the Shoot spec, the addon chart is not deployed. For example the 
```yaml
spec:
  addons:
    kubernetesDashboard:
      enabled: false
```

We were wondering - if it is disabled by default on the gardener API side, then should the addon be enabled by default in the Shoot creation dialog?

/cc @vlerenc @g-pavlov
