### ISSUE TITLE
Providing Feedback, Requesting Features, and Reporting Bugs link 

### ISSUE THREAD

**Issue by freegroup** [gardener/dashboard#65]
It would be fine if we provide a fast link to the github repo in the Dashboard UI
to report feature requests or bugs

<img width="617" alt="bildschirmfoto 2018-04-24 um 10 07 14" src="https://user-images.githubusercontent.com/1155039/39174341-bfb458be-47a7-11e8-8df2-19e33987cf92.png">

**Comment by petersutter** [comment]
Hi, what is displayed here is configurable in the backend configuration of the dashboard under the path frontend -> helpMenuItems.

```
frontend:
  helpMenuItems:
  - title: GitHub
    icon: mdi-github-box
    url: https://github.com/gardener/dashboard
```

I will add it to the dashboard instance you are referring to
