### ISSUE TITLE
Access Restrictions

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#689]
**What would you like to be added**:
Give users the ability to select access restrictions (for gardener operators) for their shoot, depending on the selected region. This should be configurable.
E.g. on the UI it could look like the following (texts are just an example and for better understanding of the requested feature)
<img width="1751" alt="Screenshot 2020-05-08 at 16 33 44" src="https://user-images.githubusercontent.com/5526658/81416230-b5fb3200-9149-11ea-8cc1-48d8367d9c77.png">

The dashboard's helm chart configuration could look like the following:
`values.yaml`:
```yaml
accessRestrictions:
  eu-access:
    title: EU Access # can be in markdown format
    description: | # can be in markdown format
      EU Access is an optional service that Gardener ...
    options:
      24-7-support-cluster-addons:
        title: No personal data is used as ...
        description: |
          If you can't comply, only third-level/dev support ...
      24-7-support-cluster-nodes:
        title: No personal data is stored in any ...
        description: |
          If you can't comply, only third-level/dev support ...
  foo:
    title: Foo
    description: lorem ipsum
  bar:
    title: Bar
    description: lorem ipsum
```

---

The following change requests are related to the gardener component and can be followed up in the issue https://github.com/gardener/gardener/issues/2306 but are mentioned here for completeness:

The selected options should be added to the shoot spec as following:
```yaml
kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
metadata:
  namespace: garden-bar
  name: foo
spec:
  accessRestrictions:
    eu-access-standard:
    - 24-7-support-cluster-nodes
    foo: []
```

In addition, the `region` of the `CloudProfile` has to be extended with an `accessRestrictions` field.
- This way we can validate the shoot resource and only allow the change if the region has a corresponding accessRestrictions field in the CloudProfile
- On the UI the checkboxes would only appear only for the respective regions.
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: CloudProfile
name: aws
regions:
  - name: ca-central-1
    zones:
    - name: ca-central-1a
    - name: ca-central-1b
  - name: eu-central-1
    accessRestrictions:
      - eu-access
      - foo
    zones:
    - name: eu-central-1a
    - name: eu-central-1b
    - name: eu-central-1c
  - name: eu-north-1
    accessRestrictions:
      - eu-access
    zones:
    - name: eu-north-1a
    - name: eu-north-1b
    - name: eu-north-1c
```

As described above the shoot validation needs to be extended so that in case an `accessRestriction` is set, it ensures that the selected region has a corresponding accessRestrictions field in the corresponding `CloudProfile`

**Why is this needed**:
In order to fulfil GDPR requirements, shoot owners should have the possibility to restrict access to their shoots in order to protect personal data.

**Comment by holgerkoser** [comment]
It looks very good. The only thing I would change is, just have at least 2-4px space between `title` and `description` of the accessRestriction `options` since the title is not a real title here.

**Comment by petersutter** [comment]
I have updated the screenshot in the description

**Comment by vlerenc** [comment]
Thank you, great! If you want to be open for the future and the taints/tolerations idea makes no sense/cannot be put into action, then maybe `annotations` instead of `accessRestrictions` would be more flexible. Also, why is it `eu-access-standard` and not `eu-access`? And how would the shoot spec look in more details in regards to the 8x5 bullet points? BTW, I would call them rather ...`-cluster-addons` and ...`-cluster-nodes`. WDYT?

**Comment by petersutter** [comment]
> If you want to be open for the future and the taints/tolerations idea makes no sense/cannot be put into action, then maybe annotations instead of accessRestrictions would be more flexible.

What do you mean with that, can you make an example? More flexible in what regards?

Regarding the second point:
It doesn't really matter as it's just configuration and the above should act as an example. Anyhow I have updated the examples like the following:
- `eu-access-standard` -> `eu-access`
- option `eu-access-24-7-cluster` -> `24-7-support-cluster-addons` (a prefix is not really needed as it's an option of `eu-access`)
- option `eu-access-24-7-node` -> `24-7-support-cluster-nodes` (a prefix is not really needed as it's an option of `eu-access`)

When we take the above example and you just select EU Access and do not check the two checkboxes, this would result in the shoot spec as
```yaml
spec:
  accessRestrictions:
    eu-access: []
```
which basically means you get eu-access compliant support with 24x7 support for the control plane and 8x5 support for the cluster-addons and 8x5 support for the cluster-nodes

If EU Access is enabled and both checkboxes checked, this would result in the shoot spec as
```yaml
spec:
  accessRestrictions:
    eu-access:
    - 24-7-support-cluster-addons
    - 24-7-support-cluster-nodes
```

**Comment by vlerenc** [comment]
@petersutter I am still a bit confused by the terms, why they include 24-7 when this is not the "main thing", but EU access is (later we could very well have an European SRE team) and how or that SRE from outside the EU would have to look out for what is not there (the `24-7-...` keys; it's far easier to miss that something is not there than it is to miss that something is there).

Let me make two counter proposals, one with taints & tolerations that has the disadvantage we talked about out-of-band (on the phone), but which "fits" somewhat into the taints concept that seeds have already today (cc @rfranzke) and one that borrows from the metaphor of capabilities (=supports) & requirements (=requires).

### (1) Taints & Tolerations

Example of a cloud profile that is unrestricted in use:

```
  regions:
  - name: pangaea-north-1
    zones:
    - name: pangaea-north-1a
    - name: pangaea-north-1b
    - name: pangaea-north-1c
    taints:
    - key: seed.gardener.cloud/unrestricted
```

Bonus: If we go down this path, we could also apply other taints such as the existing ones to protect/hide an entire region:

```
    - key: seed.gardener.cloud/protected
    - key: seed.gardener.cloud/invisible
```

Anyway, now let's take a look at a region that is free for all shoots and EU Access shoots in particular:

```
  regions:
  - name: pangaea-north-1
    zones:
    - name: pangaea-north-1a
    - name: pangaea-north-1b
    - name: pangaea-north-1c
    taints:
    - key: seed.gardener.cloud/unrestricted
    - key: seed.gardener.cloud/eu-access
```

Note: We can now implement something that would transport the taints to the seeds and piggyback on the taints concept there and how the scheduler can work with taints (ok, I don't know the code in detail, but from first principle, this sounds reasonable to me, WDYT @danielfoehrKn ?):

```
spec:
  taints:
  - key: seed.gardener.cloud/unrestricted
  - key: seed.gardener.cloud/eu-access
```

Much like we have today such taints there, e.g.:

```
spec:
  taints:
  - key: seed.gardener.cloud/protected
  - key: seed.gardener.cloud/invisible
```

OK, so how does the shoot look? A shoot without EU Access would specify:

```
spec:
  tolerations:
  - key: seed.gardener.cloud/unrestricted
```

A shoot with EU Access would specify:

```
spec:
  tolerations:
  - key: seed.gardener.cloud/eu-access
```

And in the case that the owner cannot confirm that cluster resources and nodes are free of personal data, it would look this this:

```
spec:
  tolerations:
  - key: seed.gardener.cloud/eu-access
  - key: support.gardener.cloud/cluster-addons-eu-access
  - key: support.gardener.cloud/cluster-nodes-eu-access
```

This would clearly distinguish between the technical seed requirement (use only European seeds) and the human support requirements (cluster addons and nodes can only be supported by people within Europe, i.e. if they see that, it means "hands-of-outside-europe"). The distinction is in the `seed` vs `support` and the details at the end of the key.

Pro: Partial reuse of the existing taints concept.
Pro: More flexible than `accessRestrictions`, because that word expresses too much intent/narrows down the use very much.
Con: Very awkward `unrestricted` taint necessary.

### (2) Capabilities & Requirements

Example of a cloud profile that support EU Access (if it doesn't, there is no capabilities section for now):

```
  regions:
  - name: pangaea-north-1
    zones:
    - name: pangaea-north-1a
    - name: pangaea-north-1b
    - name: pangaea-north-1c
    capabilities:
    - key: seed.gardener.cloud/eu-access
```

Optional: Either let the scheduler access the capabilities directly of the region in the cloud profile or "transfer" the capabilities to the seed like so (in parallel to the taints that may be there as well by the way):

```
spec:
  capabilities:
  - key: seed.gardener.cloud/eu-access
```

A shoot with EU Access would specify:

```
spec:
  requirements:
  - key: seed.gardener.cloud/eu-access
```

And in the case that the owner cannot confirm that cluster resources and nodes are free of personal data, it would look this this:

```
spec:
  requirements:
  - key: seed.gardener.cloud/eu-access
  - key: support.gardener.cloud/cluster-addons-eu-access
  - key: support.gardener.cloud/cluster-nodes-eu-access
```

Pro: No awkward `unrestricted` taint necessary.
Pro: More flexible than `accessRestrictions`, because that word expresses too much intent/narrows down the use very much.
Con: New concept in addition to the taints.

**Comment by rfranzke** [comment]
I think trying to stick to taints/tolerations makes sense instead of adding a new, very similar concept, but I'm not really sure yet how can work with above proposal.
Generally (in Kubernetes (and that's also how we will implement it as part of gardener/gardener#2193)), *all* taints must be tolerated for a pod/shoot to become eligible for being scheduled to a node/seed.

Hence, I don't know how this can work in practice:

```yaml
spec:
  taints:
  - key: seed.gardener.cloud/unrestricted
  - key: seed.gardener.cloud/eu-access
```

If I understand correctly, what we want to achieve is that
a) all regions/seeds can be used by default (if the user doesn't care about EU access-only)
b) only selected regions/seeds may be used if the user cares about EU access-only

Out of this, isn't the only option to taint those regions/seeds that are not eligible for EU access-only? EU access-only regions don't need any taints. Also, by leveraging the taint/tolerations effects (`NoSchedule`, `NoExecute`) it could look like this:

```yaml
  regions:
  # a region NOT eligible for eu-access-only
  - name: pangaea-north-1
    zones:
    - name: pangaea-north-1a
    - name: pangaea-north-1b
    - name: pangaea-north-1c
    taints:
    - key: access-restrictions.region.gardener.cloud/eu-access-only
      effect: NoExecute
  # a region eligible for eu-access-only
  - name: pangaea-south-1
    zones:
    - name: pangaea-south-1a
    - name: pangaea-south-1b
    - name: pangaea-south-1c
```

By default, newly created shoots tolerate the `access-restrictions.region.gardener.cloud/eu-access-only, NoExecute` taint:

```yaml
spec:
  tolerations:
  - key: access-restrictions.region.gardener.cloud/eu-access-only
    effect: NoExecute
```

This allows them to be scheduled to both `pangaea-north-1` and `pangaea-south-1`. If the user decides that he wants EU access-only then this tolerations should be removed. This will restrict the list of possible regions/seeds to `pangaea-south-1` only.

As part of gardener/gardener#2193 I'm working on a `ShootTolerationRestriction` admission plugin that allows default/whitelist tolerations per project (https://github.com/gardener/gardener/issues/2193#issuecomment-624449483), similar to how the `PodTolerationRestriction` admission plugin allows default/whitelist tolerations per namespace. Additionally, the `PodTolerationRestriction` plugin allows to configure cluster-wide defaults and whitelists. We could implement the same so that every newly created shoot gets above toleration.

**Comment by vlerenc** [comment]
Minor comments:
1. I have not any `effect` in my examples, because I looked at the current taints for seeds such as the `soil-kubernikus` that only has `key`s only.
2. Also, I picked `seed.gardener.cloud/eu-access` as a name because the other taint keys in the seed have this pattern. You suggested `key: access-restrictions.region.gardener.cloud/eu-access-only`, which looks quite different. You may have your reasons, but that's why my proposal looks like that above.

> If I understand correctly, what we want to achieve is that
> a) all regions/seeds can be used by default (if the user doesn't care about EU access-only)
> b) only selected regions/seeds may be used if the user cares about EU access-only

Yes.

> Out of this, isn't the only option to taint those regions/seeds that are not eligible for EU access-only? EU access-only regions don't need any taints.

You are of course right. I somehow tried to find a way to "flag" the EU seeds, rather than "flagging" the Non-EU seeds. So, sure, flagging the non-EU seeds is an option, but we must be aware of that when we add new regions. It's easy to miss adding the taint to non-EU seeds and the outcome is an EU shoot on a non-EU region. If however, I miss to add the other taint on an EU seed, nothing serious happens.

> If the user decides that he wants EU access-only then this tolerations should be removed.

The same applies here. If you don't add the toleration, it's EU Access, which is hard to understand (also for SRE/DevOps who are the ones that must check it - manually at first).

Question: In both proposals, we have the issue that current automation of stakeholders may not break. Would we default that, would we default it to "global", if we see a cluster without tolerations?

Final remark: If taints & tolerations "suck", then forget the proposal. I was just suggesting it because "adding a new, very similar concept" (@rfranzke's comment as well) may be something we want to avoid.

**Comment by rfranzke** [comment]
While discussing about it internally, @tim-ebert brought up that taints/tolerations might not be the right concept for this requirement, and I tend to agree (while writing up above proposal it "felt" not too well), and you also asked about it in your last reply.
Instead, he suggested that this requirement could be solved by piggy-backing on the label selector approach.

In Kubernetes, pods may state a `nodeSelector` with labels that match to nodes. Similarly, we can have a `seedSelector` in our shoot spec. Seeds in EU-access compliant regions will be labeled with e.g.

```
access-restrictions.region.gardener.cloud/eu-access-only: "true"
```

(I don't care about the concrete names now). The shoot spec would look as follows:

```yaml
spec:
  seedSelector:
    matchLabels:
      access-restrictions.region.gardener.cloud/eu-access-only: "true"
```

The Dashboard would only show the "Enable EU access" checkbox if there are seeds that have this label.

Would this work/fulfil all requirements?

**Comment by vlerenc** [comment]
Yes, absolutely, that's what I meant, but in a better from, when I replied originally:
> If you want to be open for the future and the taints/tolerations idea makes no sense/cannot be put into action, then maybe annotations instead of accessRestrictions would be more flexible. 

So, yes, if you are fine to introduce a new concept then strikeout/replace ~~annotations~~ with labels and add means to specify a label selector of even something like affinities (`requiredDuringScheduling`).

**Comment by vlerenc** [comment]
So, the proposal would then look like this?

### (3) Label Selectors

Example of a cloud profile region that supports EU Access (if it doesn't, there is no labels section for now):

```
  regions:
  - name: pangaea-north-1
    zones:
    - name: pangaea-north-1a
    - name: pangaea-north-1b
    - name: pangaea-north-1c
    labels:
    - key: seed.gardener.cloud/eu-access
      value: true
```

...or...

```
    labels:
    - seed.gardener.cloud/eu-access: true
```

Seeds would then get the labels populated:

```
metadata:
  labels:
  - seed.gardener.cloud/eu-access: true
```

A shoot with EU Access would specify:

```
spec:
  seedSelector:
    matchLabels:
      seed.gardener.cloud/eu-access: true
```

...or maybe use something like `shootAffinity` and `requiredDuringScheduling`?

**Comment by tim-ebert** [comment]
Yes, the CloudProfile could possibly go with something like this.
>     labels:
>       seed.gardener.cloud/eu-access: true

And then I would probably go with the `seedSelector` field in the `ShootSpec`.

Though, in our internal discussion there were some concerns about blowing up the CloudProfile resources with all of these additional labels. @timuthy suggested to think about adding a new resource, which can be used to configure regions, that can be used for "eu-access-only".
Also gardener (or even some extension?) might want to act differently on Shoot's which are specifying "eu-access-only" (e.g. add different `Roles` for operators to the Shoot namespace or whatever), so I think it would make sense to still add an annotation for that additionally to the `seedSelector` (which will only be used for scheduling).

**Comment by vlerenc** [comment]
I am not sure whether the new labels would really justify an additional resource, considering that only a few regions would get such labels and the cloud profiles are already large @tim-ebert @timuthy . It's where we describe, in a programmatic way, information that must be accessible to stakeholders. A new resource is effort and needs also to be exposed to them as well, if it contains such information.

As for the shoots, we anyways haven't added the support requirements yet.

So you suggest, for the shoot, something like this?

```
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  annotations:
    seed.gardener.cloud/eu-access: true
    support.gardener.cloud/cluster-addons-eu-access: true
    support.gardener.cloud/cluster-nodes-eu-access: true
  ...
spec:
  seedSelector:
    matchLabels:
      seed.gardener.cloud/eu-access: true
  ...
```

If the stakeholder can confirm, that no personal information is stored in the ETCD or on the nodes (and she is fine with worldwide support), the `support.gardener.cloud` annotations would be `false` or missing, indicating that support may be given worldwide/doesn't have to be given only from within the EU.

Is that OK for everybody?

**Comment by tim-ebert** [comment]
> I am not sure whether the new labels would really justify an additional resource

Yeah, probably not. That were just some first thoughts...

> So you suggest, for the shoot, something like this?

Yes, something like that would be good, I guess.

**Comment by vlerenc** [comment]
So, shall we sign off on proposal (3) then @rfranzke , @petersutter , @timuthy , @tim-ebert , @grolu , @holgerkoser ? Maybe by means of a 👍 or 👎 (and comment) at this comment?

### (3) Label Selectors

Example of a cloud profile region that supports EU Access (if it doesn't, there is no labels section for now):

```
  regions:
  - name: pangaea-north-1
    zones:
    - name: pangaea-north-1a
    - name: pangaea-north-1b
    - name: pangaea-north-1c
    labels:
    - seed.gardener.cloud/eu-access: true
```

Seeds would then get the labels populated automatically:

```
metadata:
  labels:
  - seed.gardener.cloud/eu-access: true
```

A shoot with EU Access would look like this:

```
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  annotations:
    seed.gardener.cloud/eu-access: true
    support.gardener.cloud/cluster-addons-eu-access: true
    support.gardener.cloud/cluster-nodes-eu-access: true
  ...
spec:
  seedSelector:
    matchLabels:
      seed.gardener.cloud/eu-access: true
  ...
```

If the stakeholder can confirm, that no personal information is stored in the ETCD or on the nodes (and she is fine with worldwide support), the `support.gardener.cloud` annotations would be gone, indicating that support may be given worldwide/doesn't have to be given only from within the EU.

**Comment by petersutter** [comment]
We are mostly fine with 3. Additionally here would be our proposal for the dashboard configuration and below some minor remarks

**Dashboard config:**
Input fields are only visible if the CloudProfile has a corresponding label (with `'true'` value).
For the `accessRestriction`, the path `spec.seedSelector.matchLabels[key]` will be set with the corresponding value mapping.
For the options, the path `metadata.annotations[key]` will be set with the corresponding value mapping.
```yaml
accessRestrictions:
  - title: EU Access # can be in markdown format
    description: | # can be in markdown format
      EU Access is an optional service that Gardener ...
    label:
      key: seed.gardener.cloud/eu-access
      valueMapping:
        true: 'true'
        false: 'false'
        default: 'false'
    options:
      - title: No personal data is used as ...
        description: |
          If you can't comply, only third-level/dev support ...
        annotation: 
          key: support.gardener.cloud/cluster-addons-eu-access
          valueMapping:
            true: 'false'
            false: 'true'
            default: 'true'
      - title: No personal data is stored in any ...
        description: |
          If you can't comply, only third-level/dev support ...
        annotation:
          key: support.gardener.cloud/cluster-nodes-eu-access
          valueMapping:
            true: 'false'
            false: 'true'
            default: 'true'
```

**CloudProfile**:
mostly the same as your proposal, but labels should either be an object or a list, not both
```yaml
  regions:
  - name: pangaea-north-1
    zones:
    - name: pangaea-north-1a
    - name: pangaea-north-1b
    - name: pangaea-north-1c
    labels:
      seed.gardener.cloud/eu-access: 'true'
```

or just use a list
```yaml
 labels:
 - seed.gardener.cloud/eu-access
```

**Shoot** with EU Access:
`seed.gardener.cloud/eu-access: true` in annotations is redundant, why do we need this? We only want to set one field for each input field in the dashboard, otherwise it makes it more complicated
