### ISSUE TITLE
Secret shown as 'currently unused' when there are Shoots using it

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/dashboard#701]
**What happened**:
Cloud provider Secret shown as 'currently unused' when there are Shoots using it. This happens when the SecretBinding `.metadata.name` != Secret `.metadata.name`.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Create `Secret`
```yaml
apiVersion: v1
data:
  accessKeyID: "accessKeyID"
  secretAccessKey: "secretAccessKey"
kind: Secret
metadata:
  name: shoot-aws-secret-bar
  namespace: garden-baz
type: Opaque
```

2. Create `SecretBinding`
```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: SecretBinding
metadata:
  name: shoot-aws-secret-foo
  namespace: garden-baz
  labels:
    cloudprofile.garden.sapcloud.io/name: aws
secretRef:
  name: shoot-aws-secret-bar
  namespace: garden-baz
```

3. Create `Shoot`
```yaml
kind: Shoot
apiVersion: core.gardener.cloud/v1beta1
metadata:
  name: test
  namespace: garden-baz
spec:
  # [...]
  secretBindingName: shoot-aws-secret-foo
```

4. Ensure that the `shoot-aws-secret-bar` Secret in the dashboard is shown as `shoot-aws-secret-bar (currently unused)`

**Anything else we need to know**:

**Environment**:
Dashboard version: `1.42.0-dev-22049d66`
