### ISSUE TITLE
`cloudprofile.garden.sapcloud.io/name` label should not be mandatory

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/dashboard#781]
**What would you like to be added**:
Currently the dashboard does not show Secrets under `<host>/namespace/<namespace>/secrets/` when the SecretBinding does not have the `cloudprofile.garden.sapcloud.io/name` label.

From end user perspective it is not okay that you need to label the SecretBinding in order to be able to see it in the dashboard (and then edit it).
I would expect to create a SecretBinding with any means and to be able to see it in the dashboard without applying additional labels.
P.S. I also realise that the SecretBinding or Secret don't have a field that indicates the provider type which is required for the sorting by provider in the secrets page.

**Steps to reproduce**:

1. Create Secret and SecretBinding that does not have this label

```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Secret
metadata:
  name: crazy-botany
  namespace: garden-foo
type: Opaque
data:
  # omitted
---
apiVersion: core.gardener.cloud/v1beta1
kind: SecretBinding
metadata:
  name:  crazy-botany
  namespace: garden-foo
secretRef:
  name: crazy-botany
  namespace: garden-foo
EOF
```

2. Go to `<host>/namespace/<namespace>/secrets/` and ensure that only SecretBindings that have the label are shown
