### ISSUE TITLE
Volume size is not configurable for cloudprofiles without volume types.

### ISSUE THREAD

**Issue by vpnachev** [gardener/dashboard#799]
**What happened**:
I have tried to create a Shoot cluster via the Dashboard for a cloud provider that has no volume types in its cloudprofile. But volume size dialog is hidden 
![image](https://user-images.githubusercontent.com/6798531/93060177-73f37700-f67a-11ea-969a-c4b2f138b726.png)
However, this cloud provider do support configurable volume size and I can set it via the YAML editor
```yaml
...
    workers:
      - name: worker-e3q72
        machine:
          type: m1.smallhdd
          image:
            name: coreos
            version: 2512.3.0
        maximum: 2
        minimum: 1
        maxSurge: 1
        maxUnavailable: 0
        volume:
          size: 80Gi
...
```

**What you expected to happen**:
To be able to configure the volume size even when volume types are missing in the cloudprofile.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know**:

**Environment**:
