### ISSUE TITLE
Worker group update fails when user specifies duplicating zones

### ISSUE THREAD

**Issue by mvladev** [gardener/dashboard#812]
**What happened**:

User tries to change the image version of a worker group. The following error occurred:

> admission webhook "validation.aws.provider.extensions.gardener.cloud" denied the request: networks.zones: Forbidden: removing zones is not allowed 

**What you expected to happen**:

Worker is changed.

**How to reproduce it (as minimally and precisely as possible)**:

Create a cluster with a specific worker - it contains 3 availability zones from which 2 are the same:

```yaml
workers:
- name: cpu-worker
  machine:
    type: m5.4xlarge
    image:
      name: gardenlinux
      version: 27.0.1
  maximum: 3
  minimum: 3
  maxSurge: 1
  maxUnavailable: 0
  volume:
    type: gp2
    size: 200Gi
  zones:
    - ap-northeast-1a
    - ap-northeast-1c
    - ap-northeast-1c
```

and try to change the image in the dashboard.

**Anything else we need to know**:

The operation succeeds with the YAML editor. I would guess that the dashboard tries to remove the duplicating zone when doing the Patch operation and it ends up with:

```yaml
  zones:
    - ap-northeast-1a
    - ap-northeast-1c
```

which fails.

**Environment**:
