### ISSUE TITLE
Make github origins configurable

### ISSUE THREAD

**Issue by petersutter** [gardener/dashboard#883]
**What would you like to be added**:
Add github configuration option to specify the allowed github origins
```yaml
gitHub:
  allowedOrigins:                                                                                                                
  - https://avatar.github-e.example.com
  - https://media.github-e.example.com
```

**Why is this needed**:
To not hardcode the allowed github origins for the CSP
