### ISSUE TITLE
Using TLS in ingress needs certificates to be specified

### ISSUE THREAD

**Issue by morremeyer** [gardener/dashboard#990]
**What happened**: With b9f6822b28ae16d5784494a58063698a4bf19d90, when one wants the Ingress to have a `spec.tls` section, `tls` needs to be specified in the values. This disables the possibility to have a `spec.tls` section in the ingress without specifying certificates, which is needed when using e.g. cert-manager.

**What you expected to happen**: Having a `spec.tls` section without explicitly specifying certificates should be possible

**How to reproduce it (as minimally and precisely as possible)**: Use any version newer than or equal to b9f6822b28ae16d5784494a58063698a4bf19d90 and not specify `tls`.

**Proposal**:

I propose to move the ingress TLS configuration to the one that is generated by `helm create`. It looks like this:

``` 
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
```

I would then add a `.crt` and `.key` field to the `.hosts` range so that certificates can be explicitly specfied.

With this, we could then specify:

```
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
  tls:
    - secretName: dashboard-secret
      crt: "optional cert" # if set, requires 'key' to be specified too and will create secret with name 'secretName'
      key: "optional key" # if set, requires 'crt' to be specified too and will create secret with name 'secretName'
      hosts:
        - dashboard.example.com
```

I’d like some feedback for that - if it is deemed a good idea, I’ll submit a PR.
